# Generated by Django 4.1.6 on 2024-04-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('special_offer', models.BooleanField(default=False, verbose_name='Специальное предложение')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('expires_in', models.DateField(verbose_name='Дата окончания')),
                ('percentage', models.PositiveSmallIntegerField(verbose_name='Процент скидки')),
                ('in_discount', models.BooleanField(default=False, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='ActionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тэг акции',
                'verbose_name_plural': 'Тэги акции',
            },
        ),
        migrations.CreateModel(
            name='OnlineAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ф.И.О')),
                ('book_date', models.DateField(verbose_name='Дата записи')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Онлайн заявка',
                'verbose_name_plural': 'Онлайн заявки',
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория фотогалереи',
                'verbose_name_plural': 'Категории фотогалереи',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.photogallerycategory', verbose_name='Категория')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Фотографии галереи',
            },
        ),
        migrations.CreateModel(
            name='ActionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_images', to='clinics.action', verbose_name='Акция')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото акции',
                'verbose_name_plural': 'Фото акции',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(blank=True, to='clinics.actiontag', verbose_name='Тэги'),
        ),
    ]
