# Generated by Django 5.0.6 on 2024-06-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_article_desc_alter_news_desc_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='image',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='title',
        ),
        migrations.AddField(
            model_name='diploma',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Файл диплома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diploma',
            name='specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='clinics.specialist', verbose_name='Врач к которому принадлежит диплом !'),
            preserve_default=False,
        ),
    ]
