# Generated by Django 5.0.6 on 2024-06-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_remove_diploma_image_remove_diploma_title_and_more'),
        ('products', '0003_alter_product_down_desc_alter_product_top_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='image',
        ),
        migrations.CreateModel(
            name='StoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='products.product')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clinics.story')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
    ]
