# Generated by Django 4.1.6 on 2024-05-16 13:15

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_characteristic_manufacturer_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='down_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Нижнее описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Верхнее описание'),
        ),
    ]
